In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [2]:
pop_file = "data.csv"

pop_df = pd.read_csv(pop_file)

In [3]:
pop_df

,rank,State,Pop,Growth,Pop2018,Pop2010,growthSince2010,Percent,density
0,1,California,39937489,0.0096,39557045,37320903,0.0701,0.1194,256.3727
1,2,Texas,29472295,0.0268,28701845,25242679,0.1676,0.0881,112.8204
2,3,Florida,21992985,0.0326,21299325,18845785,0.1670,0.0658,410.1256
3,4,New York,19440469,-0.0052,19542209,19400080,0.0021,0.0581,412.5211
4,5,Pennsylvania,12820878,0.0011,12807060,12711158,0.0086,0.0383,286.5449
5,6,Illinois,12659682,-0.0064,12741080,12840762,-0.0141,0.0379,228.0243
6,7,Ohio,11747694,0.0050,11689442,11539327,0.0181,0.0351,287.5038
7,8,Georgia,10736059,0.0206,10519475,9711810,0.1055,0.0321,186.6719
8,9,North Carolina,10611862,0.0220,10383620,9574293,0.1084,0.0317,218.2702
9,10,Michigan,10045029,0.0049,9995915,9877535,0.0170,0.0300,177.6655
10,11,New Jersey,8936574,0.0031,8908520,8799624,0.0156,0.0267,1215.1991
11,12,Virginia,8626207,0.0127,8517685,8023680,0.0751,0.0258,218.4403
12,13,Washington,7797095,0.0347,7535591,6742902,0.1563,0.0233,117.3272
13,14,Arizona,7378494,0.0288,7171646,6407774,0.1515,0.0221,64.9550
14,15,Massachusetts,6976597,0.0108,6902149,6566431,0.0625,0.0209,894.4355
15,16,Tennessee,6897576,0.0188,6770010,6355301,0.0853,0.0206,167.2748
16,17,Indiana,6745354,0.0080,6691878,6490436,0.0393,0.0202,188.2810
17,18,Missouri,6169270,0.0070,6126452,5995976,0.0289,0.0185,89.7453
18,19,Maryland,6083116,0.0067,6042718,5788642,0.0509,0.0182,626.6731
19,20,Wisconsin,5851754,0.0066,5813568,5690479,0.0283,0.0175,108.0497
20,21,Colorado,5845526,0.0263,5695564,5048281,0.1579,0.0175,56.4011
21,22,Minnesota,5700671,0.0159,5611179,5310843,0.0734,0.0170,71.5922
22,23,South Carolina,5210095,0.0248,5084127,4635656,0.1239,0.0156,173.3174
23,24,Alabama,4908621,0.0042,4887871,4785448,0.0257,0.0147,96.9221
24,25,Louisiana,4645184,-0.0032,4659978,4544532,0.0221,0.0139,107.5175
25,26,Kentucky,4499692,0.0070,4468402,4348200,0.0348,0.0135,113.9566
26,27,Oregon,4301089,0.0263,4190713,3837532,0.1208,0.0129,44.8086
27,28,Oklahoma,3954821,0.0030,3943079,3759632,0.0519,0.0118,57.6547
28,29,Connecticut,3563077,-0.0027,3572665,3579125,-0.0045,0.0107,735.8689
29,30,Utah,3282115,0.0383,3161105,2775334,0.1826,0.0098,39.9430
30,31,Iowa,3179849,0.0075,3156145,3050767,0.0423,0.0095,56.9284
31,32,Nevada,3139658,0.0347,3034392,2702464,0.1618,0.0094,28.5993
32,33,Arkansas,3038999,0.0084,3013825,2921978,0.0400,0.0091,58.4030
33,34,Puerto Rico,3032165,-0.0510,3195153,3721525,-0.1852,0.0091,876.6016
34,35,Mississippi,2989260,0.0009,2986530,2970536,0.0063,0.0089,63.7056
35,36,Kansas,2910357,-0.0004,2911505,2858213,0.0182,0.0087,35.5968
36,37,New Mexico,2096640,0.0006,2095428,2064588,0.0155,0.0063,17.2850
37,38,Nebraska,1952570,0.0121,1929268,1829536,0.0672,0.0058,25.4161
38,39,Idaho,1826156,0.0410,1754208,1570773,0.1626,0.0055,22.0969
39,40,West Virginia,1778070,-0.0154,1805832,1854214,-0.0411,0.0053,73.9691
40,41,Hawaii,1412687,-0.0055,1420491,1363963,0.0357,0.0042,219.9419
41,42,New Hampshire,1371246,0.0109,1356458,1316777,0.0414,0.0041,153.1605
42,43,Maine,1345790,0.0055,1338404,1327632,0.0137,0.0040,43.6336
43,44,Montana,1086759,0.0230,1062305,990722,0.0969,0.0033,7.4668
44,45,Rhode Island,1056161,-0.0011,1057315,1053938,0.0021,0.0032,1021.4323
45,46,Delaware,982895,0.0163,967171,899595,0.0926,0.0029,504.3073
46,47,South Dakota,903027,0.0236,882235,816165,0.1064,0.0027,11.9116
47,48,North Dakota,761723,0.0022,760077,674710,0.1290,0.0023,11.0393
48,49,Alaska,734002,-0.0047,737438,713906,0.0281,0.0022,1.2863
49,50,District of Columbia,720687,0.0260,702455,605085,0.1911,0.0022,11814.5410
50,51,Vermont,628061,0.0028,626299,625880,0.0035,0.0019,68.1416
51,52,Wyoming,567025,-0.0185,577737,564483,0.0045,0.0017,5.8400

In [4]:
pop_df = pop_df[['State','Pop','density']]
pop_df

                   State       Pop     density
0             California  39937489    256.3727
1                  Texas  29472295    112.8204
2                Florida  21992985    410.1256
3               New York  19440469    412.5211
4           Pennsylvania  12820878    286.5449
5               Illinois  12659682    228.0243
6                   Ohio  11747694    287.5038
7                Georgia  10736059    186.6719
8         North Carolina  10611862    218.2702
9               Michigan  10045029    177.6655
10            New Jersey   8936574   1215.1991
11              Virginia   8626207    218.4403
12            Washington   7797095    117.3272
13               Arizona   7378494     64.9550
14         Massachusetts   6976597    894.4355
15             Tennessee   6897576    167.2748
16               Indiana   6745354    188.2810
17              Missouri   6169270     89.7453
18              Maryland   6083116    626.6731
19             Wisconsin   5851754    108.0497
20              Colorado   5845526     56.4011
21             Minnesota   5700671     71.5922
22        South Carolina   5210095    173.3174
23               Alabama   4908621     96.9221
24             Louisiana   4645184    107.5175
25              Kentucky   4499692    113.9566
26                Oregon   4301089     44.8086
27              Oklahoma   3954821     57.6547
28           Connecticut   3563077    735.8689
29                  Utah   3282115     39.9430
30                  Iowa   3179849     56.9284
31                Nevada   3139658     28.5993
32              Arkansas   3038999     58.4030
33           Puerto Rico   3032165    876.6016
34           Mississippi   2989260     63.7056
35                Kansas   2910357     35.5968
36            New Mexico   2096640     17.2850
37              Nebraska   1952570     25.4161
38                 Idaho   1826156     22.0969
39         West Virginia   1778070     73.9691
40                Hawaii   1412687    219.9419
41         New Hampshire   1371246    153.1605
42                 Maine   1345790     43.6336
43               Montana   1086759      7.4668
44          Rhode Island   1056161   1021.4323
45              Delaware    982895    504.3073
46          South Dakota    903027     11.9116
47          North Dakota    761723     11.0393
48                Alaska    734002      1.2863
49  District of Columbia    720687  11814.5410
50               Vermont    628061     68.1416
51               Wyoming    567025      5.8400

In [5]:
pop_df = pop_df.rename(columns={
    'State':'state',
    'Pop':'population',
    'density':'population_density'
})

In [6]:
pop_df

                   state  population  population_density
0             California    39937489            256.3727
1                  Texas    29472295            112.8204
2                Florida    21992985            410.1256
3               New York    19440469            412.5211
4           Pennsylvania    12820878            286.5449
5               Illinois    12659682            228.0243
6                   Ohio    11747694            287.5038
7                Georgia    10736059            186.6719
8         North Carolina    10611862            218.2702
9               Michigan    10045029            177.6655
10            New Jersey     8936574           1215.1991
11              Virginia     8626207            218.4403
12            Washington     7797095            117.3272
13               Arizona     7378494             64.9550
14         Massachusetts     6976597            894.4355
15             Tennessee     6897576            167.2748
16               Indiana     6745354            188.2810
17              Missouri     6169270             89.7453
18              Maryland     6083116            626.6731
19             Wisconsin     5851754            108.0497
20              Colorado     5845526             56.4011
21             Minnesota     5700671             71.5922
22        South Carolina     5210095            173.3174
23               Alabama     4908621             96.9221
24             Louisiana     4645184            107.5175
25              Kentucky     4499692            113.9566
26                Oregon     4301089             44.8086
27              Oklahoma     3954821             57.6547
28           Connecticut     3563077            735.8689
29                  Utah     3282115             39.9430
30                  Iowa     3179849             56.9284
31                Nevada     3139658             28.5993
32              Arkansas     3038999             58.4030
33           Puerto Rico     3032165            876.6016
34           Mississippi     2989260             63.7056
35                Kansas     2910357             35.5968
36            New Mexico     2096640             17.2850
37              Nebraska     1952570             25.4161
38                 Idaho     1826156             22.0969
39         West Virginia     1778070             73.9691
40                Hawaii     1412687            219.9419
41         New Hampshire     1371246            153.1605
42                 Maine     1345790             43.6336
43               Montana     1086759              7.4668
44          Rhode Island     1056161           1021.4323
45              Delaware      982895            504.3073
46          South Dakota      903027             11.9116
47          North Dakota      761723             11.0393
48                Alaska      734002              1.2863
49  District of Columbia      720687          11814.5410
50               Vermont      628061             68.1416
51               Wyoming      567025              5.8400

In [7]:
pop_df.to_csv('Pop_Stat.csv')

In [8]:
connection_string = connection_string = "postgres:postgres@localhost:5432/ETL_Proj"
engine = create_engine(f'postgresql://{connection_string}')

In [9]:
engine.table_names()

['airport', 'confirmed', 'population']

In [10]:
pop_df.to_sql(name='population', con=engine, if_exists='append', index=False)