In [7]:
import pandas as pd
import numpy as np

In [8]:
covid_file = "COVID-19_Cases_US.csv"

covid_df = pd.read_csv(covid_file)

In [9]:
covid_df

,X,Y,OBJECTID,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Recovered,Deaths,Active,Admin2,FIPS,Combined_Key,Incident_Rate,People_Tested,People_Hospitalized,UID,ISO3
0,-82.461707,34.223334,1,South Carolina,US,2020/06/05 01:33:13+00,34.223334,-82.461707,46,0,0,46,Abbeville,45001.0,"Abbeville, South Carolina, US",187.548416,NaN,NaN,84045001,USA
1,-92.414197,30.295065,2,Louisiana,US,2020/06/05 01:33:13+00,30.295065,-92.414197,462,0,26,436,Acadia,22001.0,"Acadia, Louisiana, US",744.620840,NaN,NaN,84022001,USA
2,-75.632346,37.767072,3,Virginia,US,2020/06/05 01:33:13+00,37.767072,-75.632346,966,0,12,954,Accomack,51001.0,"Accomack, Virginia, US",2989.231341,NaN,NaN,84051001,USA
3,-116.241552,43.452658,4,Idaho,US,2020/06/05 01:33:13+00,43.452658,-116.241552,823,0,22,801,Ada,16001.0,"Ada, Idaho, US",170.893317,NaN,NaN,84016001,USA
4,-94.471059,41.330756,5,Iowa,US,2020/06/05 01:33:13+00,41.330756,-94.471059,9,0,0,9,Adair,19001.0,"Adair, Iowa, US",125.838926,NaN,NaN,84019001,USA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3026,-113.906667,32.768957,3027,Arizona,US,2020/06/05 01:33:13+00,32.768957,-113.906667,1643,0,23,1620,Yuma,4027.0,"Yuma, Arizona, US",768.521940,NaN,NaN,84004027,USA
3027,-102.425867,40.003468,3028,Colorado,US,2020/06/05 01:33:13+00,40.003468,-102.425867,42,0,0,42,Yuma,8125.0,"Yuma, Colorado, US",419.203513,NaN,NaN,84008125,USA
3028,-99.169872,27.001564,3029,Texas,US,2020/06/05 01:33:13+00,27.001564,-99.169872,11,0,0,11,Zapata,48505.0,"Zapata, Texas, US",77.579519,NaN,NaN,84048505,USA
3029,-99.760508,28.866172,3030,Texas,US,2020/06/05 01:33:13+00,28.866172,-99.760508,12,0,0,12,Zavala,48507.0,"Zavala, Texas, US",101.351351,NaN,NaN,84048507,USA
3030,-101.665462,44.978819,3031,South Dakota,US,2020/06/05 01:33:13+00,44.978819,-101.665462,1,0,0,1,Ziebach,46137.0,"Ziebach, South Dakota, US",36.284470,NaN,NaN,84046137,USA

In [14]:
covid_state = covid_df.groupby('Province_State')

In [17]:
covid_state_confirmed = covid_state['Confirmed'].sum()

In [19]:
state_confirmed = pd.DataFrame(covid_state_confirmed)

In [20]:
state_confirmed

                      Confirmed
Province_State
Alabama                   19072
Alaska                      512
Arizona                   22886
Arkansas                   8425
California               122168
Colorado                  27346
Connecticut               43239
Delaware                   9746
District of Columbia       9120
Florida                   60183
Georgia                   49859
Hawaii                      655
Idaho                      2990
Illinois                 124759
Indiana                   36096
Iowa                      20806
Kansas                    10167
Kentucky                  10705
Louisiana                 41562
Maine                      2446
Maryland                  55858
Massachusetts            102063
Michigan                  58241
Minnesota                 26273
Mississippi               16560
Missouri                  14438
Montana                     539
Nebraska                  15139
Nevada                     9111
New Hampshire              4876
New Jersey               162530
New Mexico                 8353
New York                 375133
North Carolina            32075
North Dakota               2706
Ohio                      37282
Oklahoma                   6907
Oregon                     4474
Pennsylvania              78335
Rhode Island              15325
South Carolina            12415
South Dakota               5162
Tennessee                 25190
Texas                     70555
Utah                      10813
Vermont                    1026
Virginia                  47856
Washington                22729
West Virginia              2102
Wisconsin                 19892
Wyoming                     921

In [21]:
state_confirmed.to_csv('Covid_Confirmed_byState')